import { defineBlackjackProtocol } from './defineProtocol';
import { MAX_SPLITS_PER_BOX } from './lasVegasProtocol';

/** Six-deck European-style shoe — no hole card during play, no insurance. */
export const EUROPEAN_SHOE_PROTOCOL = defineBlackjackProtocol({
  protocolId: 'european-shoe',
  displayName: 'European Shoe',
  shortDescription: 'Six-deck European-style rules — no hole card peek, no insurance.',
  shoe: {
    deckCount: 6,
    minDecks: 4,
    maxDecks: 8,
    reshuffleWhenEmpty: true,
  },
  dealer: {
    standsOnSoft17: true,
    hitBelow: 17,
    standAtOrAbove: 17,
    peekOnAce: false,
    peekOnTen: false,
    description: 'Dealer stands on soft 17. No peek — hole card dealt after player actions.',
  },
  dealerDrawRule: 'Stand on soft 17; no peek; hole card dealt after players finish.',
  payouts: {
    blackjackMultiplier: 1.5,
    blackjackLabel: '3:2',
    winPays: '1:1 — stake returned plus equal winnings',
    pushPays: 'Original stake returned',
    bustLoses: 'Stake lost immediately when hand exceeds 21',
  },
  double: {
    allowed: true,
    firstTwoCardsOnly: true,
    oneCardOnly: true,
    allowedAfterSplit: true,
    allowedHardTotals: [9, 10, 11],
    description: 'Double on hard 9, 10, or 11 only; one card afterward; double after split allowed.',
  },
  split: {
    allowed: true,
    sameRankOnly: true,
    maxSplitsPerRound: MAX_SPLITS_PER_BOX,
    resplitAces: true,
    hitSplitAces: true,
    doubleAfterSplit: true,
    description: 'Split matching ranks; repeat splits up to cap; double after split allowed.',
  },
  insurance: {
    offered: false,
    maxHalfOfMainBet: true,
    payoutRatio: 2,
    payoutLabel: '2:1',
    description: 'Insurance not offered in European Shoe.',
  },
  surrender: {
    allowed: false,
    lateSurrender: false,
    earlySurrender: false,
    description: 'Surrender not offered.',
  },
  resolution: {
    compareAfterDealerCompletes: true,
    naturalBeatsNonNatural: true,
    splitHandsResolvedIndependently: true,
    description: 'Hands settle after dealer completes; naturals beat 21 in multiple cards.',
  },
  dealingRules: {
    showDealerHoleCardDuringPlay: false,
    holeCardDealtLast: true,
    description: 'No hole card during player turns — dealer second card comes after all players act.',
  },
  phaseActions: {
    byPhase: {
      betting: [],
      dealing: [],
      insurance: [],
      player: ['hit', 'stand', 'double', 'split'],
      bank: [],
      banking: [],
      'round-complete': [],
    },
  },
  supportedActions: ['hit', 'stand', 'double', 'split'],
  aidProfile: {
    id: 'european-shoe',
    label: 'European Shoe',
    description: 'Basic strategy without insurance; hole card hidden until bank turn.',
    insuranceBias: 'neutral',
  },
  defaultMinBet: 5,
  defaultMaxBet: 500,
  extensions: {
    wildCards: { enabled: false, description: 'Standard 52-card ranks only.' },
    sideBets: [],
    alteredPayouts: {},
  },
  displayRules: [
    { id: 'shoe', label: 'Shoe', value: '6 decks' },
    { id: 'dealer-s17', label: 'Dealer', value: 'Stands on soft 17; no peek' },
    { id: 'bj-pay', label: 'Blackjack', value: 'Pays 3:2 on natural 21' },
    { id: 'double', label: 'Double', value: 'Hard 9, 10, 11 only; after split OK' },
    { id: 'split', label: 'Split', value: 'Same rank; repeat splits' },
    { id: 'insurance', label: 'Insurance', value: 'Not offered' },
    { id: 'hole-card', label: 'Hole card', value: 'Hidden until bank turn' },
  ],
});
